CREATE DATABASE db_banco;
use db_banco;

-- /* CREACION DE TABLAS*/
-- TABLA PERSONA
CREATE TABLE IF NOT EXISTS PERSONA  (
    PersonaId BIGINT AUTO_INCREMENT PRIMARY KEY,
    Identificacion VARCHAR(50) NOT NULL UNIQUE,
    Nombre VARCHAR(100),
    Genero VARCHAR(20),
    Edad INT,
    Direccion VARCHAR(200),
    Telefono VARCHAR(20)
);

-- TABLA CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE (
    ClienteId BIGINT AUTO_INCREMENT PRIMARY KEY,
    Contrasena VARCHAR(100) NOT NULL,
    Estado VARCHAR(20),
    PersonaId BIGINT NOT NULL,
    FOREIGN KEY (personaId) REFERENCES Persona(personaId)
);

-- TABLA CUENTA
CREATE TABLE IF NOT EXISTS Cuenta (
    CuentaId BIGINT AUTO_INCREMENT PRIMARY KEY,
    NumeroCuenta VARCHAR(30) NOT NULL UNIQUE,
    TipoCuenta VARCHAR(30) NOT NULL,
    SaldoInicial DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    Estado VARCHAR(20),
    ClienteId BIGINT NOT NULL,
    FOREIGN KEY (ClienteId) REFERENCES Cliente(clienteId)
);

-- TABLA MOVIMIENTO
CREATE TABLE IF NOT EXISTS Movimiento (
    MovimientoId BIGINT AUTO_INCREMENT PRIMARY KEY,
    Fecha DATETIME NOT NULL,
    TipoMovimiento VARCHAR(30) NOT NULL,
    Valor DECIMAL(15,2) NOT NULL,
    Saldo DECIMAL(15,2) NOT NULL,
    CuentaId BIGINT NOT NULL,
    FOREIGN KEY (cuentaId) REFERENCES Cuenta(CuentaId)
);