CREATE TABLE IF NOT EXISTS CUENTA (
    CuentaId BIGINT AUTO_INCREMENT PRIMARY KEY,
    NumeroCuenta VARCHAR(30) NOT NULL UNIQUE,
    TipoCuenta VARCHAR(30) NOT NULL,
    SaldoInicial DECIMAL(15,2) DEFAULT 0.00,
    Estado VARCHAR(20),
    ClienteId BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS MOVIMIENTO (
    MovimientoId BIGINT AUTO_INCREMENT PRIMARY KEY,
    Fecha TIMESTAMP NOT NULL,
    TipoMovimiento VARCHAR(30) NOT NULL,
    Valor DECIMAL(15,2) NOT NULL,
    Saldo DECIMAL(15,2) NOT NULL,
    CuentaId BIGINT NOT NULL,
    FOREIGN KEY (CuentaId) REFERENCES CUENTA(CuentaId)
);